# Generated by Django 5.1.4 on 2025-01-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_podcastepisodepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PodcastEpisodepage',
        ),
    ]
