# Generated by Django 5.1.4 on 2025-01-16 12:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0009_podcastepisodepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisodepage',
            name='episode_description',
            field=wagtail.fields.RichTextField(default='A brief description or summary of the episode ', help_text='Episode description or summary here. Max of 600 characters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcastepisodepage',
            name='episode_subtitle',
            field=models.CharField(default=' episode sub-title here ', help_text='maximum of 55 characters', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcastepisodepage',
            name='episode_thumbnail_img',
            field=models.ForeignKey(help_text='Thumbnail image of the episode. Recommended dimension: 1140x570 pixels ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='podcastepisodepage',
            name='episode_title',
            field=models.CharField(default=' episode title here  ', help_text='maximum of 60 characters', max_length=60),
            preserve_default=False,
        ),
    ]
