# Generated by Django 5.1.4 on 2025-01-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0010_podcastepisodepage_episode_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisodepage',
            name='episode_thumbnail_img',
            field=models.ForeignKey(help_text='Thumbnail image of the episode. Recommended dimension: 1140x570 pixels ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
    ]
