# Generated by Django 5.1.4 on 2025-01-16 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0012_podcastepisodepage_date'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_message', models.CharField(max_length=250)),
                ('article_title', models.CharField(help_text='maximum of 120 characters', max_length=120)),
                ('article_subtitle', models.CharField(help_text='maximum of 200 characters', max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('article_thumbnail_img', models.ForeignKey(help_text='Thumbnail image for the article. Recommended dimension: 1140x570 pixels', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
