# Generated by Django 5.1.4 on 2025-01-16 17:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0013_newsarticlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticlepage',
            name='article_body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
    ]
