# Generated by Django 5.1.4 on 2025-01-16 18:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0015_alter_newsarticlepage_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticlepage',
            name='article_body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('h1', 1), ('h2', 2), ('image', 3), ('embeded_media', 4), ('url', 5), ('paragraph_with_image', 9)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'level 1 headings', 'max_length': 200}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'level 2 headings', 'max_length': 200}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 5: ('wagtail.blocks.URLBlock', (), {}), 6: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Add the text for this section', 'required': True}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Choose an image for this section', 'required': True}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Check this box to position the text on the left and the image on the right. Uncheck to reverse.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('text', 6), ('image', 7), ('text_on_left', 8)]], {})}, null=True),
        ),
    ]
