# Generated by Django 5.1.4 on 2025-01-17 14:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0023_alter_newsarticlepage_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticlepage',
            name='article_body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('h2', 1), ('h3', 2), ('image', 3), ('embeded_media', 4), ('paragraph_beside_image', 8), ('two_images', 9), ('paragraph_beside_media', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'template': 'site_app/blocks/paragraph.html'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'level 2 headings', 'max_length': 200, 'template': 'site_app/blocks/two_headings.html'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'level 3 headings', 'max_length': 200, 'template': 'site_app/blocks/three_headings.html'}), 3: ('wagtail.images.blocks.ImageBlock', [], {'template': 'site_app/blocks/image_full.html'}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'embed media files like videos, social media posts/shares etc.', 'max_height': 400, 'max_length': 200, 'max_width': 700, 'template': 'site_app/blocks/embed_media.html'}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Add the text for this section', 'required': True}), 6: ('wagtail.images.blocks.ImageBlock', [], {'help_text': 'Choose an image for this section'}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Check this box to position the text on the left and the image on the right. Uncheck to reverse.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('text', 5), ('image', 6), ('text_on_left', 7)]], {'help_text': 'image beside paragraph'}), 9: ('wagtail.blocks.StructBlock', [[('image_1', 6), ('image_2', 6)]], {'help_text': 'two images side by side'}), 10: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Choose an image for this section', 'max_height': 300, 'max_length': 200, 'max_width': 450, 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('text', 5), ('media', 10), ('text_on_left', 7)]], {'help_text': 'paragraph beside embeded media'})}, null=True),
        ),
    ]
